"""empty message

Revision ID: 6b4b7b2c0798
Revises: 3ada94f75811
Create Date: 2025-11-01 11:55:48.379018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4b7b2c0798'
down_revision = '3ada94f75811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('overall',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('accurate', 'partially_correct', 'missing_info', 'hallucinated', 'other', name='feedbackmessages'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('overall',
               existing_type=sa.Enum('accurate', 'partially_correct', 'missing_info', 'hallucinated', 'other', name='feedbackmessages'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
